# -*- coding: utf-8 -*-
"""ds_midterm_2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dxq88SG2MNzGyjIQVDumpscZlXUnctfq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('https://drive.google.com/uc?export=download&id=1D7modlbAhaMwQlVwHJDQ4vYlvugleAKp')

df.head()

#dtype 확인
df.info()

#NaN 행 삭제
df = df.dropna()

#행 이름 수정
df.rename(columns = {'Mid-term':'Type 1','Unnamed: 2':'Type 2 Q1', 'Unnamed: 3':'Type 2 Q2', 'Unnamed: 4':'Type 2 Q3', 'Unnamed: 5':'Sum'}, inplace=True)
df.head()

#float to int
df = df.astype(np.int64)
df.info()

#column to index
df = df.set_index('학번')
df.head()

#통계량 확인
df.describe()

#boxplot으로 시각화
fig, ax = plt.subplots(figsize=(10, 6))
ax.boxplot(df['Sum'])
ax.set_xticklabels(["Total"])
ax.set_ylabel("Score")

plt.show()